/**
* EasyCanvas 0.1
* @author Matthieu BOHEAS
* @date 03-03-2013
*/
(function(){window.ec={LANG:'fr',DEBUG:false,extend:function(that,p){var fnTest=/xyz/.test(function(){xyz;})?/\bparent\b/:/.*/;var parent=p.prototype;var prop=that.prototype;var prototype={};var type=that.prototype.info.type.split('.')[1];for(var name in prop){if(typeof(prop[name])=='function'&&typeof(parent[name])=='function'&&fnTest.test(prop[name]))
{prototype[name]=(function(name,fn){return function(){var tmp=this.parent;this.parent=parent[name];var ret=fn.apply(this,arguments);this.parent=tmp;return ret;};})(name,prop[name]);}
else
{prototype[name]=prop[name];}}
for(var name in parent){if(!prototype[name]&&name!='to'+type){prototype[name]=parent[name];}}
that.prototype.info.parent=p.prototype.info;that.prototype=prototype;return;},ready:function(fn,stages){if(!fn){return;}
var f=null;f=function(e){if(document.removeEventListener){document.removeEventListener('DOMContentLoaded',f,false);}
else if(document.detachEvent){document.detachEvent('DOMContentLoaded',f,false);}
fn();};if(document.addEventListener){document.addEventListener('DOMContentLoaded',f,false);}
else if(document.attachEvent){document.attachEvent('DOMContentLoaded',f,false);}},_set_requestAnimFrame:function(){window.requestAnimFrame=(function(){return(window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(callback){window.setTimeout(callback,1000/60);});})();}};window.ec._set_requestAnimFrame();ec.Mouse={getAbsolutePosition:function(e){return new ec.Point({x:e.clientX,y:e.clientY});},getPosition:function(e){return new ec.Point({x:e.layerX+(document.documentElement.scrollLeft?document.documentElement.scrollLeft:document.body.scrollLeft),y:e.layerY+(document.documentElement.scrollTop?document.documentElement.scrollTop:document.body.scrollTop)});},getX:function(e){return e.layerX+(document.documentElement.scrollLeft?document.documentElement.scrollLeft:document.body.scrollLeft);},getY:function(e){return e.layerY+(document.documentElement.scrollTop?document.documentElement.scrollTop:document.body.scrollTop);}};ec.EventManager={init:function(){if(document.attachEvent){this.type=ec.EventManager.TYPE.ATTACH;}else if(document.addEventListener){this.type=ec.EventManager.TYPE.ADDLISTEN;}else{ec.Errors.log('EM001');}},type:'',events:{},app:{mouse:{pressed:false,clicked:false}},add:function(obj,evt,fn){if(!this.events[evt]){this.events[evt]=new Array();document[this.type.add](evt,this.handler,false);}
this.events[evt].push({o:obj,func:fn});},remove:function(obj,evt){for(var i in this.events[evt]){if(this.events[evt][i].o.equals(obj)){if(this.type===ec.EventManager.TYPE.ADDLISTEN){document[this.type.rem](evt,this.events[evt][i].func,false);}}}},handler:function(e){e.mousePosition=ec.Mouse.getPosition(e);e.mouseAbsPosition=ec.Mouse.getAbsolutePosition(e);for(var i in ec.EventManager.events[e.type]){ec.EventManager.events[e.type][i].func(e);}},purge:function(){throw new Error('Not Implemented Yet');},reset:function(){for(var i in ec.EventManager.app){if(typeof ec.EventManager.app[i]=='boolean'){ec.EventManager.app[i]=false;}}}};ec.EventManager.TYPE={ADDLISTEN:{add:'addEventListener',rem:'removeEventListener'},OLDIE:{add:'attachEvent',rem:'detachEvent'}};ec.EventManager.init();ec.Object=function(settings){for(var i in settings){this[i]=settings[i];}};ec.Object.prototype={info:{type:'ec.Object',getType:function(){return ec.Object;}},clone:function(){var o=new ec[this.info.type.split('.')[1]]();for(var i in this){if(typeof(i)!='function'){o[i]=this[i];}}
return o;},equals:function(o){if(o instanceof ec.Object){for(var i in this){if(this[i]!==o[i]){return false;}}
return true;}
return false;},compare:function(o){if(o.inheritsof(this.info.getType())){var t=new ec[this.info.type.split('.')[1]]();for(var i in this){if(typeof(this[i])=='number'){if(this[i]>o[i]){t[i]=1;}else if(this[i]<o[i]){t[i]=-1;}else{t[i]=0;}}else if(typeof(o[i])=='object'){if(o[i].inheritsof){t[i]=this[i].compare(o[i]);}}}
return t;}},toJSON:function(){return JSON.stringify(this);},inheritsof:function(type){return this._getInheritance(this.info).match(new RegExp(type.prototype.info.type))==type.prototype.info.type;},_getInheritance:function(info){return info.parent!=null?info.type+'|'+this._getInheritance(info.parent):info.type;},toString:function(){return this.info.type;}};ec.Color=function(settings){ec.Object.call(this,settings);};ec.Color.prototype={info:{type:'ec.Color',getType:function(){return ec.Color;}},r:0,g:0,b:0,a:1,toHexa:function(){return'#'+((1<<24)+(this.r<<16)+(this.g<<8)+this.b).toString(16).slice(1);},toString:function(){return'rgba( '+this.r+', '+this.g+', '+this.b+', '+this.a+')';},inverts:function(){this.r=Math.abs(this.r-255);this.g=Math.abs(this.g-255);this.b=Math.abs(this.b-255);return this;},equals:function(o){return this.r==o.r&&this.g==o.g&&this.b==o.b&&this.a==o.a;},compare:function(o){var r=0,g=0,b=0;if(this.r>o.r){r=1;}else if(this.r<o.r){r=-1;}
if(this.g>o.g){g=1;}else if(this.g<o.g){g=-1;}
if(this.b>o.b){b=1;}else if(this.b<o.b){b=-1;}
if(this.a>o.a){a=1;}else if(this.a<o.a){a=-1;}
return new ec.Color({r:r,g:g,b:b,a:a});},clone:function(){return new ec.Color({r:this.r,g:this.g,b:this.b,a:this.a});}};ec.Color.invert=function(o){return new ec.Color({r:Math.abs(o.r-255),g:Math.abs(o.g-255),b:Math.abs(o.b-255),a:o.a});};ec.Color.random=function(){return new cie.Color(Math.random()*256,Math.random()*256,Math.random()*256,1);};ec.extend(ec.Color,ec.Object);ec.Color.BLACK=function(){return new ec.Color({name:'black'});};ec.Color.WHITE=function(){return new ec.Color({r:255,g:255,b:255,name:'white'});};ec.Color.RED=function(){return new ec.Color({r:255,name:'red'});};ec.Color.GREEN=function(){return new ec.Color({g:255,name:'green'});};ec.Color.BLUE=function(){return new ec.Color({b:255,name:'blue'});};ec.Color.YELLOW=function(){return new ec.Color({r:255,g:255,name:'yellow'});};ec.Color.MAGENTA=function(){return new ec.Color({r:255,b:255,name:'magenta'});};ec.Color.AQUA=function(){return new ec.Color({g:255,b:255,name:'aqua'});};ec.Color.ORANGE=function(){return new ec.Color({r:255,g:165,name:'orange'});};ec.Color.PURPLE=function(){return new ec.Color({r:160,g:32,b:240,name:'purple'});};ec.Color.PINK=function(){return new ec.Color({r:255,g:192,b:203,name:'pink'});};ec.Color.Gray=function(factor){return(new ec.Color({name:'Gray '+factor,r:factor,g:factor,b:factor}));};ec.Point=function(settings){if(settings){ec.Object.call(this,settings);}};ec.Point.prototype={info:{type:'ec.Point',getType:function(){return ec.Point;}},x:0,y:0,equals:function(o){if(o.inheritsof(ec.Point)){return this.x==o.x&&this.y==o.y;}
return false;},compare:function(o){if(o.inheritsof(ec.Point)){var x=0,y=0;if(this.x>o.x){x=1;}else if(this.x<o.x){x=-1;}
if(this.y>o.y){y=1;}else if(this.y<o.y){y=-1;}
return new ec.Point({x:x,y:y});}
return null;},toString:function()
{return'{ x: '+this.x+', y: '+this.y+' }';},toVector2:function(){return new ec.Vector2({x:this.x,y:this.y});},clone:function(){return new ec.Point({x:this.x,y:this.y});}};ec.extend(ec.Point,ec.Object);ec.Vector2=function(settings){ec.Point.call(this,settings);};ec.Vector2.prototype={info:{type:'ec.Vector2',getType:function(){return ec.Vector2;}},adds:function(value){if(typeof(value)=='number'){this.x+=value;this.y+=value;}else if(value.info&&value.inheritsof(ec.Point)){this.x+=value.x;this.y+=value.y;}
return this;},substracts:function(value){if(typeof(value)=='number'){this.x-=value;this.y-=value;}else if(value.info&&value.inheritsof(ec.Point)){this.x-=value.x;this.y-=value.y;}
return this;},multiplies:function(value){if(typeof(value)=='number'){this.x*=value;this.y*=value;}else if(value.info&&value.inheritsof(ec.Point)){this.x*=value.x;this.y*=value.y;}
return this;},divides:function(value){if(typeof(value)=='number'){this.x/=value;this.y/=value;}
else if(value.info&&value.inheritsof(ec.Point)){this.x/=value.x;this.y/=value.y;}
return this;},distance:function(o){if(o.inheritsof(ec.Point)){return Math.sqrt(Math.pow(this.x-o.x,2)+Math.pow(this.y-o.y,2));}
return NaN;},distanceSquared:function(o){if(o.inheritsof(ec.Point)){return Math.pow(this.x-o.x,2)+Math.pow(this.y-o.y,2);}
return NaN;},compare:function(o){if(o.inheritsof(ec.Point)){var x=0,y=0;if(this.x>o.x){x=1;}else if(this.x<o.x){x=-1;}
if(this.y>o.y){y=1;}else if(this.y<o.y){y=-1;}
return new ec.Vector2({x:x,y:y});}},clone:function(){return new ec.Vector2({x:this.x,y:this.y});}};ec.Vector2.add=function(v1,v2){return new ec.Vector2({x:v1.x+v2.x,y:v1.y+v2.y});};ec.Vector2.substract=function(v1,v2){return new ec.Vector2({x:v1.x-v2.x,y:v1.y-v2.y});};ec.Vector2.multiply=function(v1,v2){return new ec.Vector2({x:v1.x*v2.x,y:v1.y*v2.y});};ec.Vector2.divide=function(v1,v2){return new ec.Vector2({x:v1.x/v2.x,y:v1.y/v2.y});};ec.Vector2.distance=function(v1,v2){if(v1.inheritsof(ec.Point)&&v2.inheritsof(ec.Point)){return Math.sqrt(Math.pow(v2.x-v1.x,2)+Math.pow(v2.y-v1.y,2));}
return NaN;};ec.Vector2.distanceSquared=function(v1,v2){var v=v1.clone();return v.distanceSquared(v2);};ec.Vector2.One=function(){return new Vector2({x:1,y:1});};ec.extend(ec.Vector2,ec.Point);ec.Size=function(settings){if(settings){ec.Object.call(this,settings);}};ec.Size.prototype={info:{type:'ec.Size',getType:function(){return ec.Size;}},width:0,height:0,equals:function(o){if(o instanceof ec.Size){return this.width==o.width&&this.height==o.height;}else if(typeof o=='number'){return this.width==o&&this.height==o;}
return false;},toString:function(){return'{ width: '+this.width+', height: '+this.height+' }';},compare:function(o){if(o.inheritsof(ec.Size)){var w=0,h=0;if(this.width>o.width){w=1;}else if(this.width<o.width){w=-1;}
if(this.height>o.height){h=1;}else if(this.height<o.height){h=-1;}
return new ec.Size({width:w,height:h});}},clone:function(){return new ec.Size({width:this.width,height:this.height});}};ec.extend(ec.Size,ec.Object);ec.counter=0;ec.Shape=function(settings){this.currentPosition=new ec.Point();this.position=new ec.Point();this.random=Math.random();this.float={};for(var i in settings){switch(i){case'x':case'y':this.position[i]=settings[i];break;case'width':case'height':this.size[i]=settings[i];break;case'speed':case'amplitude':this.float[i]=settings[i];break;default:this[i]=settings[i];break;}}
if(ec.EventManager){if(this.clickable){ec.EventManager.add(this,'mousedown',this.events.click.down.bind(this));ec.EventManager.add(this,'mouseup',this.events.click.up.bind(this));}
if(this.draggable){ec.EventManager.add(this,'mousedown',this.events.drag.begin.bind(this));ec.EventManager.add(this,'mousemove',this.events.drag.move.bind(this));ec.EventManager.add(this,'mouseup',this.events.drag.end.bind(this));this.counter=ec.counter++;}}};ec.Shape.prototype={info:{type:'ec.Shape',getType:function(){return ec.Shape;}},position:null,fill:null,stroke:null,lineWidth:1,clickable:false,draggable:false,float:{speed:null,amplitude:null},random:0,update:function(data){if(this.clickable&&this.onpressed&&this.isPressed){this.onpressed(data);}
if(this.clickable&&this.onclick&&this.isClicked){this.onclick(data);}
this.currentPosition.x=this.position.x;if(this.float.speed&&this.float.amplitude){this.currentPosition.y=this.position.y+Math.cos(data.timer*(2*this.float.speed))*this.float.amplitude;}else{this.currentPosition.y=this.position.y;}},draw:null,events:{click:{down:function(e){if(this.contains(e.mousePosition)){this.isPressed=true;if(this.onPressed){this.onPressed(e);}
ec.EventManager.app.mouse.pressed=true;}else{this.isPressed=false;}},up:function(e){if(this.contains(e.mousePosition)&&this.isPressed&&!this.isDragging){this.isPressed=false;ec.EventManager.app.mouse.pressed=false;this.isClicked=true;if(e.which==3&&ec.DEBUG){console.log(this);return false;}
if(this.onClicked){this.onClicked(e);}}else{this.isClicked=false;}}},drag:{begin:function(e){if(e.which==1){if(this.contains(e.mousePosition)){this.isDragging=true;this.isPressed=true;ec.EventManager.app.mouse.pressed=true;this.last=ec.Vector2.substract(this.position,e.mousePosition);}else{this.isPressed=false;this.isDragging=false;}}},move:function(e){if(this.isDragging){ec.EventManager.app.mouse.pressed=false;this.position.x=e.mousePosition.x+this.last.x;this.position.y=e.mousePosition.y+this.last.y;this.isPressed=false;}},end:function(e){if(this.isDragging){this.position.x=e.mousePosition.x+this.last.x;this.position.y=e.mousePosition.y+this.last.y;this.isDragging=false;}}},compare:function(o){if(o.inheritsof){if(o.inheritsof(ec.Shape)){var type=this.info.type.split('.')[1];return new ec[type]({position:this.position.compare(o.position),currentPosition:this.currentPosition.compare(o.currentPosition)});}}}}};ec.extend(ec.Shape,ec.Object);ec.Text=function(settings){this.value='';this.currentPosition=new ec.Point();ec.Object.call(this,settings);};ec.Text.prototype={info:{type:'ec.Text',getType:function(){return ec.Text;}},value:null,fill:null,stroke:null,lineWidth:1,font:'Verdana',size:30,style:'',currentPosition:null,update:function(data){this.currentPosition.y=this.position.y;data.context.font=this.size+'px '+this.font+' '+this.style;this.currentPosition.x=this.position.x-data.context.measureText(this.value).width/2;},draw:function(data){var ctx=data.context;ctx.font=this.size+'px '+this.font+' '+this.style;if(this.fill){ctx.fillStyle=this.fill instanceof ec.Color?this.fill.toHexa():this.fill;ctx.fillText(this.value,this.currentPosition.x,this.currentPosition.y);}
if(this.stroke){ctx.strokeStyle=this.stroke instanceof ec.Color?this.stroke.toHexa():this.stroke;ctx.lineWidth=this.lineWidth;ctx.strokeText(this.value,this.currentPosition.x,this.currentPosition.y);}},compare:function(o){if(o.inheritsof&&o.inheritsof(ec.Text)){var text=0,font=0,size=0,style=0;if(this.value!==o.value){if(this.value.length>o.value.length){text=1;}else if(this.value.length<o.value.length){text=-1;}}
if(this.size>o.size){size=1;}else if(this.size<o.size){size=-1;}
if(this.font!==o.font){if(this.font.length>o.font.length){font=1;}else if(this.font.length<o.font.length){font=-1;}}
if(this.style!==o.style){if(this.style.length>o.style.length){style=1;}else if(this.style.length<o.style.length){style=-1;}}
return new ec.Text({value:text,font:font,size:size,style:style});}},clone:function(){var fill=this.fill instanceof ec.Color?this.fill.clone:this.fill;var stroke=this.stroke instanceof ec.Color?this.stroke.clone:this.stroke;return new ec.Text({position:this.position.clone(),stroke:stroke,fill:fill,font:this.font,lineWidth:this.lineWidth,style:this.style,size:this.size,value:this.value});}};ec.extend(ec.Text,ec.Object);ec.Rectangle=function(settings){this.size=new ec.Size();ec.Shape.call(this,settings);};ec.Rectangle.prototype={info:{type:'ec.Rectangle',getType:function(){return ec.Rectangle;}},size:null,currentPosition:null,draw:function(data){var ctx=data.context;if(this.fill){ctx.fillStyle=this.fill instanceof ec.Color?this.fill.toHexa():this.fill;ctx.fillRect(this.currentPosition.x,this.currentPosition.y,this.size.width,this.size.height);}
if(this.stroke){ctx.strokeStyle=this.stroke instanceof ec.Color?this.stroke.toHexa():this.stroke;ctx.lineWidth=this.lineWidth;ctx.strokeRect(this.currentPosition.x,this.currentPosition.y,this.size.width,this.size.height);}},contains:function(o){var tp=this.currentPosition?this.currentPosition:this.position;if(o.inheritsof(ec.Point)){return(o.x>tp.x&&o.x<tp.x+this.size.width&&o.y>tp.y&&o.y<tp.y+this.size.height);}else if(o.inheritsof(ec.Rectangle)){var p=o.currentPosition?o.currentPosition:o.position;return(p.x>tp.x&&p.y>tp.y&&p.x+o.size.width<=tp.x+this.size.width&&p.y+o.size.height<=tp.y+this.size.height);}
return false;},equals:function(o){if(o.inheritsof(ec.Rectangle)){return o.position.x==this.position.x&&o.position.y==this.position.y&&o.size.width==this.size.width&&o.size.height==this.size.height;}},compare:function(o){if(!o.inheritsof(ec.Rectangle)){return null;}
var x=0,y=0,w=0,h=0;if(this.position.x>o.position.x){x=1;}else if(this.position.x<o.position.x){x=-1;}
if(this.position.y>o.position.y){y=1;}else if(this.position.y<o.position.y){y=-1;}
if(this.size.width>o.size.width){w=1;}else if(this.size.width<o.size.width){w=-1;}
if(this.size.height>o.size.height){h=1;}else if(this.size.height<o.size.height){h=-1;}
return new ec.Rectangle({position:new ec.Point({x:x,y:y}),size:new ec.Size({width:w,height:h})});},toString:function(){return this.info.type+' '+this.position.toString()+' '+this.size.toString();},toJSON:function(){return JSON.stringify(this);},clone:function(){var fill=this.fill instanceof ec.Color?this.fill.clone:this.fill;var stroke=this.stroke instanceof ec.Color?this.stroke.clone:this.stroke;return new ec.Rectangle({position:this.position.clone(),size:this.size.clone(),fill:fill,stroke:stroke,amplitude:this.float.amplitude,speed:this.float.speed,clickable:this.clickable,draggable:this.draggable});}};ec.extend(ec.Rectangle,ec.Shape);ec.Circle=function(settings){ec.Shape.call(this,settings);};ec.Circle.prototype={info:{type:'ec.Circle',getType:function(){return ec.Circle;}},currentPosition:null,radius:0,draw:function(data){var ctx=data.context;if(this.radius>0&&this.fill||this.stroke&&this.radius>0){ctx.beginPath();ctx.arc(this.currentPosition.x,this.currentPosition.y,this.radius,0,Math.PI*2);ctx.closePath();if(this.fill){ctx.fillStyle=this.fill instanceof ec.Color?this.fill.toHexa():this.fill;ctx.fill();}
if(this.stroke){ctx.strokeStyle=this.stroke instanceof ec.Color?this.stroke.toHexa():this.stroke;ctx.lineWidth=this.lineWidth;ctx.stroke();}}},contains:function(c){var d=0,tp=this.currentPosition?this.currentPosition:this.position;if(c.inheritsof(ec.Point)){d=ec.Vector2.distance(tp,c);if(this.isClicked){console.log(d,this.radius);this.isClicked=false;}
return(d<this.radius);}else if(c.inheritsof(ec.Circle)){d=ec.Vector2.distance(tp,c.position);return d<(this.radius+c.radius);}
return false;},toString:function(){return'{ '+this.info.type+': '+this.positon.toString()+', radius: '+this.radius+' }';},equals:function(o){if(o.inheritsof(ec.Circle)){return o.position.x==this.position.x&&o.position.y==this.position.y&&this.radius==o.radius;}
return false;},compare:function(o){if(o.inheritsof(ec.Shape)){var r=0;if(this.radius>o.radius){r=1;}else if(this.radius<o.radius){r=-1;}
return new ec.Circle({position:this.position.compare(o.position),currentPosition:this.currentPosition.compare(o.currentPosition),radius:r});}
return false;},clone:function(){var fill=this.fill instanceof ec.Color?this.fill.clone:this.fill;var stroke=this.stroke instanceof ec.Color?this.stroke.clone:this.stroke;return new ec.Circle({position:this.position.clone(),radius:this.radius,fill:fill,stroke:stroke,lineWidth:this.lineWidth,amplitude:this.float.amplitude,speed:this.float.speed,clickable:this.clickable,draggable:this.draggable});}};ec.extend(ec.Circle,ec.Shape);ec.Timer=function(seconds){this.base=ec.Timer.time;this.last=ec.Timer.time;this.target=seconds||0;};ec.Timer.prototype={info:{type:'ec.Timer',getType:function(){return ec.Timer;}},last:0,base:0,target:0,pausedAt:0,set:function(seconds){this.target=seconds||0;this.base=ec.Timer.time;this.pausedAt=0;},reset:function(){this.base=ec.Timer.time;this.pausedAt=0;},tick:function(){var delta=ec.Timer.time-this.last;this.last=ec.Timer.time;return(this.pausedAt?0:delta);},delta:function(){return(this.pausedAt||ec.Timer.time)-this.base-this.target;},pause:function(){if(!this.pausedAt){this.pausedAt=ec.Timer.time;}},unpause:function(){if(this.pausedAt){this.base+=ec.Timer.time-this.pausedAt;this.pausedAt=0;}}};ec.Timer._last=0;ec.Timer.time=Number.MIN_VALUE;ec.Timer.timeScale=1;ec.Timer.maxStep=0.05;ec.Timer.step=function(){var current=Date.now();var delta=(current-ec.Timer._last)/1000;ec.Timer.time+=Math.min(delta,ec.Timer.maxStep)*ec.Timer.timeScale;ec.Timer._last=current;};ec.extend(ec.Timer,ec.Object);ec.Stage=function(settings){ec.Object.call(this,settings);};ec.Stage.prototype={info:{type:'ec.Stage',getType:function(){return ec.Stage;}},timer:new ec.Timer(),layers:new Array(),update:function(){for(var i in this.layers){this.layers[i].update(this);}},draw:function(){for(var i in this.layers){this.layers[i].draw(this);}},run:function(){this.isRunning=true;ec.Timer.step();this.timer.reset();this._loop();},_loop:function(){if(this.isRunning){ec.EventManager.reset();ec.Timer.step();this.update();ec.Timer.step();this.draw();window.requestAnimFrame(this._loop.bind(this));}},add:function(o){this.layers.push(o);}};ec.extend(ec.Stage,ec.Object);ec.Layer=function(settings){this.lastMouse.rel=new ec.Point();this.lastMouse.abs=new ec.Point();if(settings.canvas){this.canvas=document.getElementById(settings.canvas);this.canvas.width=settings.width;this.canvas.height=settings.height;this.context=this.canvas.getContext('2d');delete settings.canvas;}
this.components=new Array();ec.Object.call(this,settings);};ec.Layer.prototype={canvas:null,context:null,width:0,height:0,offset:new ec.Point(),info:{type:'ec.Layer',getType:function(){return ec.Layer;}},fixed:false,components:null,mouseupCorrection:false,lastMouse:{rel:null,abs:null,pointed:false},add:function(component){this.components.push(component);if(!this.mouseupCorrection&&component.clickable||component.draggable&&!this.mouseupCorrection){var that=this;this.canvas.oncontextmenu=function(e){e.preventDefault();return false;};ec.EventManager.add(this,'mousemove',(function(e){this.lastMouse.rel=e.mousePosition;this.lastMouse.abs=e.mouseAbsPosition;}).bind(this));ec.EventManager.add(document,'mouseup',function(){if(!ec.EventManager.app.mouse.pressed){that.canvas.style.cursor='default';}});this.mouseupCorrection=true;}},update:function(stage){this.lastMouse.pointed=false;for(var i=0;i<this.components.length;i++){if(this.components[i].contains&&!this.lastMouse.pointed){if(this.components[i].contains(this.lastMouse.rel)){if(this.components[i].isDragging){this.canvas.style.cursor='move';}else{this.canvas.style.cursor='pointer';}
this.lastMouse.pointed=true;}else{this.canvas.style.cursor='default';}}
if(this.components[i].update){this.components[i].update({context:this.context,timer:stage.timer.delta(),mouse:this.lastMouse});}}},draw:function(stage){this.context.clearRect(0,0,this.width,this.height);for(var i=0;i<this.components.length;i++){if(this.components[i].draw){this.components[i].draw({context:this.context,timer:stage.timer.delta(),mouse:this.lastMouse});}}}};ec.extend(ec.Layer,ec.Object);})();